### PR TITLE
Create Bubble Sort

### PR DESCRIPTION
**Pull request by arizkinewbie**

### CODE REVIEW

**Comment by V35HR4J** [comment]
HI,
Thankyou for submitting but your filename is a bit confusing, it is Bubble Sort (Data Lari Mahasiswa).py but the code seem to be in C++.
Could you mind fixing and commiting again?

**Comment by arizkinewbie** [comment]
ow yeah, sorry i fixing again

**Comment by V35HR4J** [comment]
.

**Comment by arizkinewbie** [comment]
invalid? why sir?

**Comment by V35HR4J** [comment]
Sorry, it was mistakenly labeled
just Removed it
Can you please send new pull request by commiting it into c++ directory.
Thanks in advance.✌️✌️

**Comment by arizkinewbie** [comment]
okay sir

**Pull request closed without merging**
